const car = [
  {
    id: 1,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://auto.ndtvimg.com/car-images/gallery/honda/jazz/exterior/honda-jazz-front-view.jpg?v=2016-09-16',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 2,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://content.icarcdn.com/styles/large/s3/field/gallery/2015/02/honda-jazz-7_1.jpeg?itok=g5VSdjs8',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 3,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://auto.ndtvimg.com/car-images/gallery/honda/jazz/exterior/honda-jazz-front-view.jpg?v=2016-09-16',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 4,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://content.icarcdn.com/styles/large/s3/field/gallery/2015/02/honda-jazz-7_1.jpeg?itok=g5VSdjs8',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 5,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://auto.ndtvimg.com/car-images/gallery/honda/jazz/exterior/honda-jazz-front-view.jpg?v=2016-09-16',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 6,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://auto.ndtvimg.com/car-images/gallery/honda/jazz/exterior/honda-jazz-front-view.jpg?v=2016-09-16',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 7,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://content.icarcdn.com/styles/large/s3/field/gallery/2015/02/honda-jazz-7_1.jpeg?itok=g5VSdjs8',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 8,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://auto.ndtvimg.com/car-images/gallery/honda/jazz/exterior/honda-jazz-front-view.jpg?v=2016-09-16',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 9,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://content.icarcdn.com/styles/large/s3/field/gallery/2015/02/honda-jazz-7_1.jpeg?itok=g5VSdjs8',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 10,
    title: 'Honda Jazz 2015',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://auto.ndtvimg.com/car-images/gallery/honda/jazz/exterior/honda-jazz-front-view.jpg?v=2016-09-16',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
]


export { car }